"""
schemas_to_dbt.py
=================
Converts pandera schema files (generated by home-task/eda/explore.py) into
dbt-compatible schema.yml files, one per source.

Output lands in data-platform/models/staging/<model_name>.yml, one file per model,
co-located with its .sql file — ready to be extended with descriptions and tests.

Run:
    python home-task/eda/schemas_to_dbt.py
"""

import os
from pathlib import Path
import yaml

os.environ["DISABLE_PANDERA_IMPORT_WARNING"] = "True"

BASE_DIR    = Path(__file__).parent.parent.parent
SCHEMAS_DIR = Path(__file__).parent / "schemas"
OUT_DIR     = BASE_DIR / "data-platform" / "models" / "staging"

# pandera dtype → Snowflake/dbt type
DTYPE_MAP = {
    "int64":         "integer",
    "int32":         "integer",
    "Int64":         "integer",
    "float64":       "float",
    "Float64":       "float",
    "object":        "varchar",
    "string":        "varchar",
    "bool":          "boolean",
    "boolean":       "boolean",
    "datetime64[ns]": "timestamp_ntz",
    "datetime64[ns, UTC]": "timestamp_tz",
}

# Source name → dbt staging model name
MODEL_NAME = {
    "marketplace_licenses":     "stg_marketplace_licenses",
    "marketplace_transactions": "stg_marketplace_transactions",
    "amplitude_events":         "stg_amplitude_events",
}


def load_pandera_schema(schema_path: Path):
    """Exec the pandera schema script and return the schema object."""
    ns = {}
    exec(schema_path.read_text(), ns)
    return ns["schema"]


def map_dtype(dtype: str) -> str:
    return DTYPE_MAP.get(str(dtype), "varchar")


def build_dbt_model(source_name: str, schema) -> dict:
    columns = []
    for col_name, col in schema.columns.items():
        entry = {
            "name": col_name,
            "data_type": map_dtype(col.dtype),
        }
        tests = []
        if not col.nullable:
            tests.append("not_null")
        if col.unique:
            tests.append("unique")
        if tests:
            entry["tests"] = tests
        columns.append(entry)

    return {
        "name": MODEL_NAME.get(source_name, f"stg_{source_name}"),
        "description": f"Staged {source_name.replace('_', ' ')} — cleaned and typed from raw source.",
        "columns": columns,
    }


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    for schema_file in sorted(SCHEMAS_DIR.glob("*_schema.py")):
        source_name = schema_file.stem.replace("_schema", "")
        print(f"[{source_name}] loading schema...", flush=True)
        schema = load_pandera_schema(schema_file)
        model = build_dbt_model(source_name, schema)
        model_name = model["name"]

        out = {"version": 2, "models": [model]}
        out_path = OUT_DIR / f"{model_name}.yml"
        with open(out_path, "w") as f:
            yaml.dump(out, f, default_flow_style=False, sort_keys=False, allow_unicode=True)

        print(f"[{source_name}] {len(model['columns'])} columns → {out_path.name} ✓", flush=True)

    print(f"\nWritten to {OUT_DIR}", flush=True)


if __name__ == "__main__":
    main()
